

const concerts = [
    { id: 1, name: "Rock Night", genre: "Rock", price: "$30", location: "London", date: "2025-04-12", imageUrl: '/EventPageImages/0066_large.webp' },
    { id: 2, name: "Metal Madness", genre: "Metal", price: "$40", location: "Berlin", date: "2025-06-23", imageUrl: '/EventPageImages/Black-Sabbath-BTTB-SQ-740x740.jpg' },
    { id: 3, name: "Alternative Echoes", genre: "Alternative Rock", price: "$25", location: "New Orleans", date: "2025-05-14", imageUrl: '/EventPageImages/Gemini_Generated_Image_3mv6w03mv6w03mv6.jpeg' },
    { id: 8, name: "Punk Attack", genre: "Punk", price: "$38", location: "Los Angeles", date: "2025-11-05", imageUrl: '/EventPageImages/Gemini_Generated_Image_64cjjf64cjjf64cj.jpeg' },
    { id: 13, name: "Rock Revival", genre: "Rock", price: "$32", location: "Manchester", date: "2026-04-20", imageUrl: '/EventPageImages/Gemini_Generated_Image_bgpipebgpipebgpi.jpeg' },
    { id: 14, name: "Metal Mayhem", genre: "Metal", price: "$42", location: "Stockholm", date: "2026-06-28", imageUrl: '/EventPageImages/Gemini_Generated_Image_lyfxgzlyfxgzlyfx.jpeg' },
    { id: 15, name: "Alternative Anthems", genre: "Alternative Rock", price: "$27", location: "Seattle", date: "2026-05-18", imageUrl: '/EventPageImages/heavy-metal-concert-poster-template-6f2464a997dc0094c7c82b005cdeaff4_screen.jpg' },
    { id: 16, name: "Hard Rock Heroes", genre: "Rock", price: "$35", location: "Detroit", date: "2026-07-15", imageUrl: '/EventPageImages/images.jpeg'},
    { id: 17, name: "Thrash Titans", genre: "Metal", price: "$45", location: "Sao Paulo", date: "2026-08-25", imageUrl: '/EventPageImages/images (1).jpeg' },
    { id: 18, name: "Indie Rock Night", genre: "Alternative Rock", price: "$30", location: "Austin", date: "2026-11-10", imageUrl: '/EventPageImages/images (2).jpeg' },
    { id: 19, name: "Heavy Metal Thunder", genre: "Metal", price: "$50", location: "Tokyo", date: "2027-01-15", imageUrl:'/EventPageImages/imagesade.jpeg' },
    { id: 20, name: "Grunge Glory", genre: "Alternative Rock", price: "$33", location: "Portland", date: "2027-02-20", imageUrl: '/EventPageImages/stock-vector-strong-and-fearless-rose-flower-eagle-rock-and-roll-music-festival-poster-music-world-tour-2466677729.jpg' },
    { id: 21, name: "Punk Chaos", genre: "Punk", price: "$42", location: "Chicago", date: "2026-10-05", imageUrl: "/EventPageImages/image_7.jpeg" },
    { id: 22, name: "Rock Night", genre: "Rock", price: "$35", location: "Manchester", date: "2025-06-30", imageUrl: "/EventPageImages/image_29.jpeg" },
    { id: 23, name: "Metal Reign", genre: "Metal", price: "$49", location: "Tokyo", date: "2026-03-14", imageUrl: "/EventPageImages/image_92.jpeg" },
    { id: 24, name: "Alternative Energy", genre: "Alternative Rock", price: "$30", location: "Portland", date: "2025-12-12", imageUrl: "/EventPageImages/image_3.jpeg" },
    { id: 25, name: "Punk Madness", genre: "Punk", price: "$39", location: "Los Angeles", date: "2026-09-01", imageUrl: "/EventPageImages/image_38.jpeg" },
    { id: 26, name: "Rock Titans", genre: "Rock", price: "$40", location: "Detroit", date: "2026-04-21", imageUrl: "/EventPageImages/image_19.jpeg" },
    { id: 27, name: "Metal Fire", genre: "Metal", price: "$50", location: "Berlin", date: "2025-11-29", imageUrl: "/EventPageImages/image_95.jpeg" },
    { id: 28, name: "Alternative Chaos", genre: "Alternative Rock", price: "$28", location: "Seattle", date: "2025-07-13", imageUrl: "/EventPageImages/image_32.jpeg" },
    { id: 29, name: "Punk Anthems", genre: "Punk", price: "$44", location: "New York", date: "2026-02-18", imageUrl: "/EventPageImages/image_84.jpeg" },
    { id: 30, name: "Rock Rebellion", genre: "Rock", price: "$32", location: "London", date: "2025-05-25", imageUrl: "/EventPageImages/image_50.jpeg" },
    { id: 31, name: "Metal Riot", genre: "Metal", price: "$47", location: "Sao Paulo", date: "2026-05-16", imageUrl: "/EventPageImages/image_59.jpeg" },
    { id: 32, name: "Alternative Storm", genre: "Alternative Rock", price: "$33", location: "New Orleans", date: "2027-03-08", imageUrl: "/EventPageImages/image_71.jpeg" },
    { id: 33, name: "Punk Blast", genre: "Punk", price: "$41", location: "Los Angeles", date: "2026-06-22", imageUrl: "/EventPageImages/image_34.jpeg" },
    { id: 34, name: "Rock Mayhem", genre: "Rock", price: "$39", location: "Manchester", date: "2026-08-30", imageUrl: "/EventPageImages/image_26.jpeg" },
    { id: 35, name: "Metal Fury", genre: "Metal", price: "$52", location: "Stockholm", date: "2026-01-04", imageUrl: "/EventPageImages/image_20.jpeg" },
    { id: 36, name: "Alternative Blast", genre: "Alternative Rock", price: "$31", location: "Austin", date: "2025-09-24", imageUrl: "/EventPageImages/image_6.jpeg" },
    { id: 37, name: "Punk Night", genre: "Punk", price: "$43", location: "Chicago", date: "2025-11-17", imageUrl: "/EventPageImages/image_0.jpeg" },
    { id: 38, name: "Rock Energy", genre: "Rock", price: "$34", location: "Detroit", date: "2027-01-28", imageUrl: "/EventPageImages/image_45.jpeg" },
    { id: 39, name: "Metal Chaos", genre: "Metal", price: "$48", location: "Berlin", date: "2027-05-03", imageUrl: "/EventPageImages/image_14.jpeg" },
    { id: 40, name: "Alternative Night", genre: "Alternative Rock", price: "$30", location: "Portland", date: "2026-10-14", imageUrl: "/EventPageImages/image_46.jpeg" },
    { id: 41, name: "Punk Thunder", genre: "Punk", price: "$45", location: "New York", date: "2026-03-30", imageUrl: "/EventPageImages/image_36.jpeg" },
    { id: 42, name: "Rock Storm", genre: "Rock", price: "$36", location: "London", date: "2025-06-05", imageUrl: "/EventPageImages/image_57.jpeg" },
    { id: 43, name: "Metal Inferno", genre: "Metal", price: "$53", location: "Tokyo", date: "2026-04-16", imageUrl: "/EventPageImages/image_68.jpeg" },
    { id: 44, name: "Alternative Inferno", genre: "Alternative Rock", price: "$32", location: "New Orleans", date: "2025-08-22", imageUrl: "/EventPageImages/image_52.jpeg" },
    { id: 45, name: "Punk Energy", genre: "Punk", price: "$39", location: "Los Angeles", date: "2027-02-06", imageUrl: "/EventPageImages/image_66.jpeg" },
    { id: 46, name: "Rock Revolution", genre: "Rock", price: "$37", location: "Manchester", date: "2026-12-11", imageUrl: "/EventPageImages/image_91.jpeg" },
    { id: 47, name: "Metal Anthem", genre: "Metal", price: "$50", location: "Sao Paulo", date: "2025-09-15", imageUrl: "/EventPageImages/image_15.jpeg" },
    { id: 48, name: "Alternative Rise", genre: "Alternative Rock", price: "$29", location: "Seattle", date: "2026-07-01", imageUrl: "/EventPageImages/image_62.jpeg" },
    { id: 49, name: "Punk Mayhem", genre: "Punk", price: "$46", location: "Chicago", date: "2026-05-20", imageUrl: "/EventPageImages/image_39.jpeg" },
    { id: 50, name: "Rock Pulse", genre: "Rock", price: "$35", location: "Detroit", date: "2026-06-08", imageUrl: "/EventPageImages/image_49.jpeg" },
    { id: 51, name: "Metal Power", genre: "Metal", price: "$51", location: "Stockholm", date: "2027-04-04", imageUrl: "/EventPageImages/image_24.jpeg" },
    { id: 52, name: "Alternative Anthem", genre: "Alternative Rock", price: "$28", location: "Austin", date: "2025-07-27", imageUrl: "/EventPageImages/image_74.jpeg" },
    { id: 53, name: "Punk Vibes", genre: "Punk", price: "$42", location: "Los Angeles", date: "2026-03-01", imageUrl: "/EventPageImages/image_1.jpeg" },
    { id: 54, name: "Rock Anthem", genre: "Rock", price: "$34", location: "London", date: "2026-05-17", imageUrl: "/EventPageImages/image_76.jpeg" },
    { id: 55, name: "Metal Devotion", genre: "Metal", price: "$47", location: "Tokyo", date: "2026-10-29", imageUrl: "/EventPageImages/image_99.jpeg" },
    { id: 56, name: "Alternative Dream", genre: "Alternative Rock", price: "$33", location: "Portland", date: "2025-10-03", imageUrl: "/EventPageImages/image_16.jpeg" },
    { id: 57, name: "Punk Echo", genre: "Punk", price: "$40", location: "New York", date: "2027-03-11", imageUrl: "/EventPageImages/image_4.jpeg" },
    { id: 58, name: "Rock Fire", genre: "Rock", price: "$36", location: "Manchester", date: "2026-02-25", imageUrl: "/EventPageImages/image_25.jpeg" },
    { id: 59, name: "Metal Pulse", genre: "Metal", price: "$49", location: "Berlin", date: "2026-08-08", imageUrl: "/EventPageImages/image_88.jpeg" },
    { id: 60, name: "Alternative Flame", genre: "Alternative Rock", price: "$30", location: "Seattle", date: "2025-11-09", imageUrl: "/EventPageImages/image_93.jpeg" }
];

export default concerts;